##################
# code/submission/aggregate_depth_proteins.sub
# Submission script for calculating the depth
# of a given set of scaffolds in a given set
# of metagenomes

# Benjamin D. Peterson
##################

request_cpus = 6
request_memory = 30GB

executable = /home/GLBRCORG/bpeterson26/HellsCanyon/code/executables/aggregate_depth_bins.sh

environment = "metagenome=$(metagenome) \
              depthDirectory=/home/GLBRCORG/bpeterson26/HellsCanyon/dataEdited/binAnalysis/depth \
              S2B_file=/home/glbrc.org/bpeterson26/HellsCanyon/dataEdited/binning/bins_hgcA_keepers/DNA_S2B.tsv \
              mappingFolder=/home/GLBRCORG/bpeterson26/HellsCanyon/dataEdited/binning/mapping \
              scripts=/home/GLBRCORG/bpeterson26/HellsCanyon/code/generalUse"

output = /home/GLBRCORG/bpeterson26/HellsCanyon/reports/outs/$(metagenome)_aggregate_depth_bins.out
error = /home/GLBRCORG/bpeterson26/HellsCanyon/reports/errs/$(metagenome)_aggregate_depth_bins.err
log = /home/GLBRCORG/bpeterson26/HellsCanyon/reports/logs/$(metagenome)_aggregate_depth_bins.log

queue metagenome from /home/GLBRCORG/bpeterson26/HellsCanyon/metadata/lists/MG_list_all.txt
