
#####################################
# metagenomeAssemblyAnalysis/calculate_depth_length_contigs.py
# Benjamin D. Peterson

# This reads in a depth file (generated by
# the depth function in samtools) and
# averages the depth of each contig.

# It requires only that you input the
# depth file.
#####################################

#####################################
# Load up libraries
#####################################
import os
import sys
import pandas as pd

#####################################
# Read in input from command line
#####################################
depth = sys.argv[1]
#depth = "KMAS001_bins_depth_raw.tsv"
filteredLength = int(sys.argv[2])
# filteredLength = 150
outputFileName = sys.argv[3]
# outputFileName = "KMAS001_bins_depth_length.tsv"

#####################################
# Open up depth file
#####################################
depthTable = pd.read_table(depth, names = ['contigs', 'locus', 'depth'])

#####################################
# Filter out residues at start of contig
#####################################
depthTable = depthTable[depthTable['locus'] >= filteredLength]


#####################################
# Filter out residues at end of contig
#####################################

# First, find the max contig length
lengthOfContig = depthTable[['contigs', 'locus']].groupby('contigs').max()
lengthOfContig.rename(columns = {'locus':'lengthOfContig'}, inplace = True)

# Save out original length
lengthOfContigOriginal = lengthOfContig
lengthOfContigOriginal

# Substract the length to filter out
lengthOfContig['maxLengthToInclude'] = lengthOfContig['lengthOfContig'] - filteredLength

# Then, join max contig length DF with depth table
depthTable = pd.merge(depthTable, lengthOfContig, on='contigs', how='outer')

# Filter out end of contig
depthTable = depthTable[depthTable['locus'] <= depthTable['maxLengthToInclude']]

depthTable = depthTable[['contigs', 'depth', 'lengthOfContig']]


#####################################
# Aggregate depth by contig
#####################################
# Find average coverage across contig
depthTable = depthTable.groupby('contigs').mean()



# Read out data
depthTable.to_csv(outputFileName, sep='\t', header = False)
